# Generated by Django 5.0.1 on 2024-01-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wajahat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
