# Generated by Django 5.0.1 on 2024-02-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_delete_wajahat_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_img',
            field=models.ImageField(blank=True, null=True, upload_to='cat_img/'),
        ),
    ]
