# Generated by Django 5.0.1 on 2024-03-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
