# Generated by Django 5.0.1 on 2024-02-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image_four',
            field=models.ImageField(default='', upload_to='product/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_three',
            field=models.ImageField(default='', upload_to='product/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_two',
            field=models.ImageField(default='', upload_to='product/'),
            preserve_default=False,
        ),
    ]
